server:
  port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service.marathon.l4lb.thisdcos.directory:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: https://api.github.com/user
