server:
  port: 8182

security:
  oauth2:
    resource:
      load-balanced: true
      user-info-uri: http://user-service/me

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/kjp2017-2?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver

schema:
  registry:
    url: http://localhost:8081

doma:
  dialect: MYSQL

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
