server:
  port: 8182

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/kjp2017-2?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver

schema:
  registry:
    url: http://localhost:8081

doma:
  dialect: MYSQL

security:
  oauth2:
    resource:
      load-balanced: true
      user-info-uri: http://user-service/me
