server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service.marathon.l4lb.thisdcos.directory:8761/eureka/

security:
  oauth2:
    client:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      load-balanced: true
      user-info-uri: http://user-service/me

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/kjp2017?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver

schema:
  registry:
    url: http://localhost:8081

doma:
  dialect: MYSQL
